---
deployment:
      tasks:
        - export DEPLOYPATH=/home/bombaze1/repositories/bombazer_klub
        - /bin/cp index.html $DEPLOYPATH #Copy specific file to destination from root
        - /bin/cp style.css $DEPLOYPATH #copy specific file from source sub folder
        - /bin cp * $DEPLOYPATH #copy all from root 
        - /bin cp /<sub_folder>/* $DEPLOYPATH #copy all from sub folder root
